### PR TITLE
feat: add fix suggestion for github-pr-review

### LINKED ISSUE #5: suggestion: black formatting suggest
## suggestion

black skip github-pr-review reviewdog's report.
That's all right.

And I suggest reporting fixed result suggestion support.

see https://github.com/reviewdog/reviewdog#diff

```shell
$ black --help


  --diff                          Don't write the files back, just output a
                                  diff for each file on stdout.
```

process: `--diff` alternate `--check` and format `diff` or fix and git diff report.

How about trying this?

### PR DESCRIPTION
**Pull request by tsuyoshicho**
close #5 

see test repo
https://github.com/tsuyoshicho/action-test-repo/pull/7

[Image from Gyazo](https://gyazo.com/6b4a8333bc15ab1441feae4d8753a754)

use tsuyoshicho/action-black develop branch same as PR branch (same commits)

---
## note

exact diff genereate need `--quiet` option.

### CODE REVIEW

**Comment by tsuyoshicho** [comment]
I think this fix is wrong.

flags add two or more items.
Need bare string.

**Comment by rickstaa** [comment]
@tsuyoshicho I noticed. I am looking at a way to revert my commit.

**Comment by rickstaa** [comment]
I found a way through the GitHub website.

**Comment by rickstaa** [comment]
@tsuyoshicho I think it now works I will merge the pull request and perform a test.

**Comment by tsuyoshicho** [comment]
Okay, test it.

**Comment by rickstaa** [comment]
@tsuyoshicho The test was successful (see https://github.com/rickstaa/action-test-repo/pull/2#event-4124598188). Thanks again for the great contribution! :tada:

**Pull request merged**
