### PR TITLE
fix: fix 'bad array subscript' error

### PR DESCRIPTION
**Pull request by rickstaa**
This pull request fixes the `bad array subscript` error that is thrown when no python files are found (see https://github.com/rickstaa/panda-gazebo/actions/runs/5269309929/jobs/9527260724). It also simplifies the codebase.

### CODE REVIEW

**Review by tsuyoshicho — APPROVED** [review]
I think it's fine

(If possible, it would be better to have others see it,
I think it would be better if there was an execution result with this content.)

You mean that we throw a warning when no python files are found?

**Comment by rickstaa** [comment]
> I think it's fine
> 
> (If possible, it would be better to have others see it, I think it would be better if there was an execution result with this content.)

You mean that we throw a warning when no python files are found? Or a verbose option that also prints the output of black to the console?

**Comment by tsuyoshicho** [comment]
@rickstaa san

It wasn't the right way to say it.

I thought it would be nice to have a test run with this fix and the results.

There is no problem with the contents.

**Comment by rickstaa** [comment]
@tsuyoshicho Ah, I see I did the following:
- Added a `verbose` variable people can use to get the black output in the GitHub action console.
- Added a warning in the console when a user inputs an empty folder.
- Added a test to see if the action does not fail when an empty folder is supplied.

Looks like all tests are now successful (see https://github.com/reviewdog/action-black/actions/runs/5291044936/jobs/9576026780?pr=62). Hope that is what you had in mind. Additionally, I performed two tests in an external repo so that you can see the changes in action:

- https://github.com/rickstaa/action-test-repo/actions/runs/5291049014/jobs/9576036169 (With verbose enabled).
- https://github.com/rickstaa/action-test-repo/actions/runs/5291093285/jobs/9576257366 (With warning).

**Review by tsuyoshicho — APPROVED** [review]
Good!
LGTM

**Review by tsuyoshicho — APPROVED** [review]
Good!
LGTM

**Pull request merged**
